### ISSUE TITLE
Update config YAML to remove JSON

### ISSUE THREAD

**Issue by jluterek** [commercetools/serverless-commercetools-plugin#11]
Consider removing the escaped JSON string from the configuration and replacing it with nested data fields.
```
   CTP_POST_BODY: '{
          "destination": {
            "type": "SQS",
            "queueUrl": "<url_to_your_queue>",
         "accessKey": "<your_key>",
         "accessSecret": "<your_secret>",
         "region": "<your_region>"
          },
         "messages": [
         {
             "resourceTypeId": "order"
         }
         ]
    }'
```

```
  CTP_POST_BODY: 
      destination:
          type: SQS
          queueUrl: "<url_to_your_queue>"
          accessKey: "<your_key>"
          accessSecret: "<your_secret>"
          region: "<your_region>"
      messages:
          - resourceTypeId: order
```
